version: "3.8"

services:
  transmission:
    image: haugene/transmission-openvpn:4.3.2
    container_name: transmission
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=${OPENVPN_CONFIG}
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      # won't be necessary when traefik is up and running, this is only to allow
      # a hole in the VPN for access to the web ui
      - LOCAL_NETWORK=192.168.86.0/24
      - TRANSMISSION_WEB_UI=flood-for-transmission
      - PUID=1000
      - PGID=1000
    volumes:
      - ${STACK_PATH}/data/downloads:/data
      - ${STACK_PATH}/data/config:/config
    ports:
      - 9091:9091
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    logging:
      driver: json-file
      options:
          max-size: 10m
    networks:
      - proxy

networks:
  proxy:
    name: home-server
    external: true