version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:2.16.2
    command: -H unix:///var/run/docker.sock
    container_name: portainer
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    env_file:
      - .env
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    labels:
      my.zone: home-server
      traefik.enable: true
      traefik.http.routers.portainer.rule: Host(`portainer.${SERVER_DOMAIN}`)
      traefik.http.routers.portainer.entrypoints: web
      traefik.http.services.portainer.loadbalancer.server.port: 9000

networks:
  proxy:
    name: home-server

volumes:
  portainer_data: