version: "3.8"

services:
  komga:
    image: gotson/komga:0.157.5
    container_name: komga
    volumes:
      - /data/komga/config:/config
      # The comics folder will be a symlink inside here. It's not passed in directly as a volume because if the mount
      # fails it will seem to komga like it got deleted and it will wipe the db. This will just give an error until it returns
      - /data/komga/data:/data
    ports:
      - 8288:8080
    user: 1000:1000
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    labels:
      my.zone: home-server
      traefik.enable: true
      traefik.http.routers.komga.rule: Host(`komga.${SERVER_DOMAIN}`)
      traefik.http.routers.komga.entrypoints: web
      traefik.http.services.komga.loadbalancer.server.port: 80

networks:
  proxy:
    name: home-server
    external: true