version: "3.8"

services:
  transmission:
    image: haugene/transmission-openvpn:4.3.2
    container_name: transmission
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=${OPENVPN_CONFIG}
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      # won't be necessary when traefik is up and running, this is only to allow
      # a hole in the VPN for access to the web ui
      - LOCAL_NETWORK=192.168.86.0/24
      - TRANSMISSION_WEB_UI=flood-for-transmission
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
    volumes:
      - ${DATA_PARENT_PATH}/data/media/downloads:/data
      - ${DATA_PARENT_PATH}/data/transmission/config:/config
    ports:
      - 9091:9091
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    logging:
      driver: json-file
      options:
          max-size: 10m
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true
    labels:
      my.zone: zone1
      traefik.enable: true

      traefik.http.routers.transmission.rule: Host(`transmission.${SERVER_DOMAIN}`)
      traefik.http.routers.transmission.entrypoints: websecure
      traefik.http.routers.transmission.service: transmission
      traefik.http.services.transmission.loadbalancer.server.port: 9091

      traefik.http.routers.radarr.rule: Host(`radarr.${SERVER_DOMAIN}`)
      traefik.http.routers.radarr.entrypoints: websecure
      traefik.http.routers.radarr.service: radarr
      traefik.http.services.radarr.loadbalancer.server.port: 7878

      traefik.http.routers.sonarr.rule: Host(`sonarr.${SERVER_DOMAIN}`)
      traefik.http.routers.sonarr.entrypoints: websecure
      traefik.http.routers.sonarr.service: sonarr
      traefik.http.services.sonarr.loadbalancer.server.port: 8989

      traefik.http.routers.lidarr.rule: Host(`lidarr.${SERVER_DOMAIN}`)
      traefik.http.routers.lidarr.entrypoints: websecure
      traefik.http.routers.lidarr.service: lidarr
      traefik.http.services.lidarr.loadbalancer.server.port: 8686

      traefik.http.routers.prowlarr.rule: Host(`prowlarr.${SERVER_DOMAIN}`)
      traefik.http.routers.prowlarr.entrypoints: websecure
      traefik.http.routers.prowlarr.service: prowlarr
      traefik.http.services.prowlarr.loadbalancer.server.port: 9696

  radarr:
    image: lscr.io/linuxserver/radarr:4.2.4
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${DATA_PARENT_PATH}/data/media:/media
      - ${DATA_PARENT_PATH}/data/radarr/config:/config
    ports:
      - 7878:7878
    restart: unless-stopped
    network_mode: service:transmission
    depends_on:
      - transmission
    security_opt:
      - no-new-privileges:true

  sonarr:
    image: lscr.io/linuxserver/sonarr:3.0.9
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${DATA_PARENT_PATH}/data/media:/media
      - ${DATA_PARENT_PATH}/data/sonarr/config:/config
    ports:
      - 8989:8989
    restart: unless-stopped
    network_mode: service:transmission
    depends_on:
      - transmission
    security_opt:
      - no-new-privileges:true

  lidarr:
    image: lscr.io/linuxserver/lidarr:1.0.2
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${DATA_PARENT_PATH}/data/media:/media
      - ${DATA_PARENT_PATH}/data/lidarr/config:/config
    ports:
      - 8686:8686
    restart: unless-stopped
    network_mode: service:transmission
    depends_on:
      - transmission
    security_opt:
      - no-new-privileges:true

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:0.4.9-develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${DATA_PARENT_PATH}/data/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    network_mode: service:transmission
    depends_on:
      - transmission
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    name: home-server
    external: true