version: "3.8"

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:2.5.3
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${DATA_PARENT_PATH}/data/config:/config
    ports:
      - 8888:80
    container_name: heimdall
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    labels:
      my.zone: home-server
      traefik.enable: true
      traefik.http.routers.heimdall.rule: Host(`dash.${SERVER_DOMAIN}`)
      traefik.http.routers.heimdall.entrypoints: websecure
      traefik.http.services.heimdall.loadbalancer.server.port: 80

networks:
  proxy:
    name: home-server
    external: true